#!/bin/bash
set -e

echo "======================================"
echo "   交易记录应用 - PWA 安装指南"
echo "======================================"
echo ""
echo "您的应用已支持 PWA（渐进式 Web 应用）！"
echo ""
echo "📱 Android 设备安装步骤："
echo "1. 使用 Chrome 浏览器访问应用"
echo "2. 点击右上角菜单（三个点）"
echo "3. 选择'添加到主屏幕'或'安装应用'"
echo "4. 确认安装"
echo ""
echo "📱 iOS 设备安装步骤："
echo "1. 使用 Safari 浏览器访问应用"
echo "2. 点击底部分享按钮（方框加箭头）"
echo "3. 向下滚动，选择'添加到主屏幕'"
echo "4. 点击'添加'确认"
echo ""
echo "💻 桌面设备安装步骤："
echo "1. 使用 Chrome 或 Edge 浏览器"
echo "2. 点击地址栏右侧的安装图标（+）"
echo "3. 或者点击右上角菜单 → '安装应用'"
echo "4. 确认安装"
echo ""
echo "======================================"
echo "   详细信息请查看 LOCAL_APP_GUIDE.md"
echo "======================================"
echo ""
echo "应用地址（本地开发）："
echo "  http://localhost:5000"
echo ""
